import "server-only";
import { and, desc, eq } from "drizzle-orm";
import { db, tenant, type TenantRow } from "./db";

export type Genre = "funny" | "horror" | "wuxia" | "both";

export interface NewTenantInput {
  id: string;
  displayName: string;
  styleKey: string;
  niche: string;
  genres: Genre;
  cadenceDays: number[];
  cadenceTz: string;
}

/** Self-serve tenants are scoped by ownerUserId the same way review-app reads are —
 *  see the `ownedBy`/`isAdmin` pattern in lib/episodes.ts. There's no admin bypass
 *  here: onboarding is a user acting on their own not-yet-active tenant, never on
 *  someone else's. */

/** Most recent tenant owned by this user that isn't fully active yet, or the most
 *  recent active one — used to decide which onboarding step (if any) to resume. */
export async function getMyLatestTenant(userId: string): Promise<TenantRow | null> {
  const [row] = await db
    .select()
    .from(tenant)
    .where(eq(tenant.ownerUserId, userId))
    .orderBy(desc(tenant.createdAt))
    .limit(1);
  return row ?? null;
}

/** Look up a tenant by its Zernio profile id, scoped to the caller — used by the
 *  connect callback, which only carries `profileId` (not our own tenant id) on
 *  the redirect Zernio sends back. */
export async function getMyTenantByProfileId(profileId: string, userId: string): Promise<TenantRow | null> {
  const [row] = await db
    .select()
    .from(tenant)
    .where(and(eq(tenant.zernioProfileId, profileId), eq(tenant.ownerUserId, userId)))
    .limit(1);
  return row ?? null;
}

/** Create the tenant row for a brand-new self-serve signup. Autonomy is always
 *  "autonomous" — never a wizard choice (locked product decision). `publish` and
 *  `zernioProfileId` start empty; the connect step fills `publish.instagram` and
 *  the profile-creation step fills `zernioProfileId` right after. */
export async function createDraftTenant(userId: string, input: NewTenantInput): Promise<TenantRow> {
  const [row] = await db
    .insert(tenant)
    .values({
      id: input.id,
      ownerUserId: userId,
      displayName: input.displayName,
      styleKey: input.styleKey,
      niche: input.niche,
      genres: input.genres,
      autonomy: "autonomous",
      cadence: { days: input.cadenceDays, time: "09:00", tz: input.cadenceTz },
      publish: {},
      active: false,
      onboardingStatus: "pending_connect",
    })
    .returning();
  return row!;
}

export async function attachZernioProfile(tenantId: string, userId: string, zernioProfileId: string): Promise<void> {
  await db
    .update(tenant)
    .set({ zernioProfileId, updatedAt: new Date() })
    .where(and(eq(tenant.id, tenantId), eq(tenant.ownerUserId, userId)));
}

/** Store the connected Instagram account and advance to pending_payment. Format
 *  is fixed at "4x5" — the only format the self-serve IG-only flow produces. */
export async function attachInstagramAccount(
  tenantId: string,
  userId: string,
  ig: { accountId: string; handle: string },
): Promise<void> {
  await db
    .update(tenant)
    .set({
      publish: { instagram: { accountId: ig.accountId, handle: ig.handle, format: "4x5" } },
      onboardingStatus: "pending_payment",
      updatedAt: new Date(),
    })
    .where(and(eq(tenant.id, tenantId), eq(tenant.ownerUserId, userId)));
}

/** Stripe webhook handlers below act on a subscription id, not a Clerk session —
 *  there is no `userId` to scope by, so these are the only tenant writes in this
 *  file that aren't ownership-checked. That's fine: the subscription/tenant ids
 *  they act on were generated by us and only ever handed to Stripe in metadata,
 *  never accepted as untrusted input from a browser. */

export async function activateTenantFromCheckout(
  tenantId: string,
  stripe: { customerId: string; subscriptionId: string },
): Promise<void> {
  await db
    .update(tenant)
    .set({
      active: true,
      onboardingStatus: "active",
      stripeCustomerId: stripe.customerId,
      stripeSubscriptionId: stripe.subscriptionId,
      stripeSubscriptionStatus: "active",
      updatedAt: new Date(),
    })
    .where(eq(tenant.id, tenantId));
}

const STATUS_MAP: Record<string, { active: boolean; onboardingStatus: "active" | "payment_failed" | "canceled" }> = {
  active: { active: true, onboardingStatus: "active" },
  trialing: { active: true, onboardingStatus: "active" },
  past_due: { active: false, onboardingStatus: "payment_failed" },
  unpaid: { active: false, onboardingStatus: "payment_failed" },
  incomplete_expired: { active: false, onboardingStatus: "canceled" },
  canceled: { active: false, onboardingStatus: "canceled" },
};

/** Sync from a Stripe subscription status change. Unknown statuses (e.g. a new
 *  Stripe status this map hasn't been updated for) deliberately deactivate
 *  rather than silently leaving a tenant posting on an unrecognized state. */
export async function syncSubscriptionStatus(stripeSubscriptionId: string, status: string): Promise<void> {
  const mapped = STATUS_MAP[status] ?? { active: false, onboardingStatus: "canceled" as const };
  await db
    .update(tenant)
    .set({
      active: mapped.active,
      onboardingStatus: mapped.onboardingStatus,
      stripeSubscriptionStatus: status,
      updatedAt: new Date(),
    })
    .where(eq(tenant.stripeSubscriptionId, stripeSubscriptionId));
}
